### ISSUE TITLE
CocoaPods Keywords

### ISSUE THREAD

**Issue by AliSoftware** [esttorhe/RxViewModel#5]
When I'm searching for MVVM on cocoa pods.org, RxViewModel doesn't show up.

Adding that keyword somewhere in your `podspec` description might help discoverability :wink:

**Comment by esttorhe** [comment]
Definitely; actually Orta commented about it but related to the `README`; hence #4 

But I think improving discoverability is a top priority.
i'm going to muster something better for the `pod` description.

Thanks :bow:

**Comment by AliSoftware** [comment]
:dancers:

**Comment by esttorhe** [comment]
I think I failed :(

Looks like it only searches on the `summary` and I updated the `description` ¯\\\_(ツ)\_/¯

**Comment by AliSoftware** [comment]
Haha damn
Le jeu. 8 oct. 2015 à 21:12, Esteban Torres <notifications@github.com> a
écrit :

**Comment by esttorhe** [comment]
and failed again… even updated the `summary` :(

**Comment by AliSoftware** [comment]
Mmmmh starting to feel strange, it should use at least `summary` keywords.

Maybe that's because you used in in backticks and those are not properly lemmatized by the search engine?

Maybe you forgot to light a candle and sacrifice a :rooster: while singing around the :fire: ?
(Probably time to invoke our shamans :tanabata_tree:  @orta or @floere to solve this mystery)

**Comment by AliSoftware** [comment]
Wait, why are you saying it failed again?
<img width="914" alt="rxviewmodel" src="https://cloud.githubusercontent.com/assets/216089/10377411/6593291c-6e03-11e5-8f53-accf67171470.png">

**Comment by esttorhe** [comment]
ahhhh; I was looking from terminal

```console
 ~/Code/…/   v0.5.0  be pod search mvvm


-> DCHMVVMKit (0.0.3)
   A MVVM develop kit for Objective-C.
   pod 'DCHMVVMKit', '~> 0.0.3'
   - Homepage: https://github.com/seraphcxl/DCHMVVMKit
   - Source:   https://github.com/seraphcxl/DCHMVVMKit.git
   - Versions: 0.0.3, 0.0.2, 0.0.1 [master repo]
```

**Comment by AliSoftware** [comment]
The `pod search` command only searches (1) locally, using the `podspecs` cloned in your `~/.cocoapods/repos/` and (2) only in the pod name iirc

To use the local search but also search in the description, use `pod search --full`. This extends the search to `summary` and `description` (and maybe even `author`, not sure)

To use the web search, that calls the search API and let the server do its search algorithm remotely and return the result instead of doing a local search, use `pod search --web`

**Comment by esttorhe** [comment]
ahhhhhhh thanks for the lesson on the `API` and the `CLI` tool :)
much appreciated :bow:

**Comment by floere** [comment]
@AliSoftware Nice explanation :)
@esttorhe Glad it worked in the end :rocket:
